### ISSUE TITLE
article needs to read

### ISSUE THREAD

**Issue by sheldonshen** [d87335903/javascript_ninja#42]
https://davidwalsh.name/nodelist-array
http://flypursue.com/jekyll/update/2016/09/21/node-vs-element.html  
http://liuecho.me/2016/01/22/%E6%AF%8F%E5%A4%A9%E4%B8%80%E6%9D%A1JS%E5%B0%8F%E7%9F%A5%E8%AF%86/
http://www.cnblogs.com/venoral/p/5293575.html
https://www.talkingcoder.com/article/6304384470053094618
http://ife.baidu.com/note/detail?noteId=765
http://web.jobbole.com/86576/
https://toddmotto.com/a-comprehensive-dive-into-nodelists-arrays-converting-nodelists-and-understanding-the-dom/

**Comment by sheldonshen** [comment]
https://davidwalsh.name/nodelist-array  Convert NodeList to Array

**Comment by d87335903** [comment]
http://flypursue.com/jekyll/update/2016/09/21/node-vs-element.html Element和Node的区别你造吗？
